name: easymp3gain
base: core20
version: '0.5.1+svn137'
summary: GUI for MP3Gain
description: |
  Graphical User Interface (GUI) for MP3Gain, VorbisGain and AACGain (enables
  you to modify the loudness level of mp3,ogg,mp4 files) / Frontend for
  MP3Gain / Grafische Benutzeroberflaeche fuer MP3Gain, VorbisGain und AACGain

grade: stable
confinement: strict

apps:
  easymp3gain:
    command: bin/desktop-launch easymp3gain-gtk
    plugs:
      - avahi-observe
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - mount-observe
      - removable-media
      - x11
    desktop: usr/share/applications/easymp3gain-gnome.desktop

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk2-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes

parts:
  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
  mp3gain:
    plugin: nil
    after: [desktop-gtk2]
    stage-snaps:
      - mp3gain
    stage:
      - usr/bin/mp3gain
      - usr/lib/x86_64-linux-gnu/*
    override-build: |
      mkdir -p ../install/usr/bin/
      cp ../install/mp3gain ../install/usr/bin/
      snapcraftctl build
  easymp3gain:
    after: [mp3gain]
    plugin: cmake
    source: https://svn.code.sf.net/p/easymp3gain/code/trunk
    source-type: svn
    override-build: |
      rm -rf ./*
      cp -R ../src/* .
      sed -i.bak -e 's|Icon=easymp3gain$|Icon=${SNAP}/usr/share/icons/hicolor/128x128/apps/easymp3gain.png|g' data/easymp3gain.desktop.in
      rm -rf build
      mkdir build
      cd build
      cmake .. -DLAZBUILD_EXE=/usr/bin/lazbuild -DLCL_VERSION=10008 -DCMAKE_INSTALL_PREFIX=../../install/usr
      make
      make install
    build-packages:
      - gcc
      - g++
      - libmpg123-dev
      - lcl
      - fpc
      - lcl-gtk2
      - libgtk2.0-dev
      - pkg-config
      - cmake
      - gettext
    organize:
      /usr/bin/easymp3gain-gtk: /usr/bin/easymp3gain-gtk
